### ISSUE TITLE
Capitalization check on Ontology registry

### ISSUE THREAD

**Issue by amedranogil** [universAAL/middleware#13] opened 2017-05-08 16:11 UTC
The capilaization of URIs should be checked (Uppercase first letter after "#" for Classes, lowercase first letter for everything else).
This will not inherently fail, but the (de)serializer does not like it otherwise and will fail (I have dealt with this problem in the past and it should be checked on the ontology tests).

**Comment by cstockloew** [comment] 2017-05-10 18:04
I'm a bit surprised that this could be a source of error. We can change the capitalization, but this should only be a convention. An error indicates that there is a bug which needs to be fixed. Can you provide an example?

**Comment by Alfiva** [comment] 2017-05-11 07:37
Also, take this chance to consolidate the upper case/lower case AAL in the "org.universAAL.ontology" part of the URIs. For instance, Lighting ontology uses "universaal" while most others use "universAAL".

**Comment by amedranogil** [comment] 2017-05-11 08:35
This happened long ago, when I was a universAAL trainee, My system (context publisher-subscriber) worked perfectly in a single node, but the system would not work for the life of it in multi node. @Alfiva pointed out about the capitalization of classes, property and instance URIs and it worked. From that point on I have always remembered to apply the convention to avoid these "undetectable" errors in multi-node systems.

**Comment by amedranogil** [comment] 2017-05-17 12:31
see https://github.com/universAAL/nativeandroid/issues/3

> Please use a string that starts with a lower case letter, like "mylamp1".

**Comment by cstockloew** [comment] 2017-05-28 14:50
I made a test with distributed lighting sample and changed lighting ontology: LightSource with lower-case class URI and brightness with upper-case URI. There have been no problems. If there is a problem, I cannot reproduce it; or, it's fixed already. Maybe it happens only if Android is involved.

As this is merely a convention or recommendation, I changed OntTestCase to fail only if there is a log message at level >= warn. But the log messages are printed for all levels.

I also added tests at info level to check the URI so that
- classes start with upper-case
- props start with lower-case
- classes and props that contain '.universAAL.' in any case do so with exactly this case
- classes and props that contain '.universAAL.' are preceeded by "ontology."

Although I have to admit that I'm not sure if this should be "universAAL" instead of "universaal". It is a domain name (which is not case-sensitive) but also the organization name....
Currently, it prints an info message if it's not "universAAL".

Anything else to check?

**Comment by Alfiva** [comment] 2017-05-29 07:51
I remember this was an old issue, so maybe it was either fixed or related to a very old version (dating back to the times when we used Jena). Anyway, if it's just a warning it's good to have ti checked as best practice. The universAAL/aal is a more recent and relevant issue though. I'm sure there is some case-sensitive mathcmaking somewhere - perhaps just Android MW but I don't remember.

**Comment by cstockloew** [comment] 2017-05-29 14:19
If you have something else we can test during ont registration, please open a new issue. I'm closing this one as the capitalization check is done.

**Closed by cstockloew** 2017-05-29 14:19 UTC
Labels: enhancement
